language: bash

services:
- docker

env:
  matrix:
  - ALPINE_VER=3.11 PYTHON_VERSION=3.6 TAGS=14.4.0,latest

script:
- make 

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - charlessoft@qq.com
    on_success: never
    on_failure: always
